version: 2

sources:
  - name: raw
    tables:
      - name: raw_posts

models:
  - name: stg_posts_incremental
    description: "Incremental staging model ingesting raw posts"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: userId
        tests:
          - not_null

  - name: posts_fact
    description: "Fact table of posts"

  - name: dim_users
    description: "Dimension table of users"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique

  - name: mart_user_analytics
    description: "User-level aggregates and metrics"
    columns:
      - name: user_id
        tests:
          - not_null
