version: 2

sources:
  - name: raw
    tables:
      - name: raw_posts

models:
  - name: stg_posts
    description: "Staging table for raw posts from JSONPlaceholder"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: userId
        tests:
          - not_null

  - name: int_posts_enriched
    description: "Intermediate enriched posts"
  - name: mart_user_posts
    description: "User-level aggregates"
